### ISSUE TITLE
Circuit diagram and how program controller IC

### ISSUE THREAD

**Issue by Kamalkant1234** [pgrady3/EasyController2#2]
Kindly share circuit diagram and how will do program controller IC wirth Arduino-IDE.

**Comment by pgrady3** [comment]
The circuit diagram is available under docs/schematic.png

The Teensy 3.2 getting started guide shows how to upload code and install the Teensyduino plugin into Arduino. [https://www.pjrc.com/teensy/first_use.html](https://www.pjrc.com/teensy/first_use.html)
